spring.application.name=platform-backend
server.port=8070

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.generate-ddl=true


#logging.level.org.springframework=DEBUG
#logging.level.org.springframework.data=DEBUG
#logging.level.org.springframework.transaction=DEBUG

#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

spring.datasource.url=jdbc:postgresql://localhost:5443/postgres?currentSchema=platform
spring.datasource.username=user
spring.datasource.password=password

spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
spring.sql.init.data-locations=classpath:sql/data.sql

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=user
spring.rabbitmq.password=password

spring.rabbitmq.fourteengames.exchange-name=xivgames_exchange
spring.rabbitmq.fourteengames.register-game-queue=register_game
spring.rabbitmq.fourteengames.register-game-binding=game.register
spring.rabbitmq.fourteengames.unlock-achievement-queue=achievement_unlock
spring.rabbitmq.fourteengames.unlock-achievement-binding=achievement.unlock

spring.rabbitmq.fourteengames.analytics-exchange=platform.events

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8180/realms/FourteenGames
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8180/realms/FourteenGames/protocol/openid-connect/certs

cors.allowed-origins=http://localhost:5173