@baseUrl = http://localhost:8080/api/games
@ttt = 11111111-1111-1111-1111-111111111111
@go = 22222222-2222-2222-2222-222222222222
@tetris = 33333333-3333-3333-3333-333333333333

### Get All Games
GET {{baseUrl}}

### Get Tic Tac Toe
GET {{baseUrl}}/{{ttt}}

### Get Go
GET {{baseUrl}}/{{go}}

### Get Tetris
GET {{baseUrl}}/{{tetris}}

### Get non-existing game
GET {{baseUrl}}/99999999-9999-9999-9999-999999999999

//Using the below emthod requires you to set a username, password and client secret.

//client secret can be found in the client (platform-backend) of keycloack
//Username = a username you created in keycloack. for ex test_user
//password = the password for that user.
### GET ACCESS TOKEN FOR A KEYCLOAC USER
POST http://localhost:8180/realms/FourteenGames/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

client_id=platform-backend&client_secret=nYNwTH09AguPkCyPk6Wt6jW2xgrBXrje&username=123&password=123&grant_type=password&scope=openid

> {%
    client.global.set("test_user_token", response.body.access_token);
%}

### Retrieve favorite game list (Empty list when no favorites)
GET {{baseUrl}}/favorite
Authorization: Bearer {{test_user_token}}

### Favorite a game
POST {{baseUrl}}/favorite/{{ttt}}
Authorization: Bearer {{test_user_token}}

### Favorite a non-existant game
POST {{baseUrl}}/favorite/99999999-9999-9999-9999-999999999999
Authorization: Bearer {{test_user_token}}

### Remove a game from favorites.
DELETE {{baseUrl}}/favorite/{{ttt}}
Authorization: Bearer {{test_user_token}}

### Remove a non-existant game from favorites.
POST {{baseUrl}}/favorite/99999999-9999-9999-9999-999999999999
Authorization: Bearer {{test_user_token}}

### Retrieve favorite game list
GET {{baseUrl}}/favorite
Authorization: Bearer {{test_user_token}}

### Retrieve specific favorite game (404 when ttt is NOT a favorite)
GET {{baseUrl}}/favorite/{{ttt}}
Authorization: Bearer {{test_user_token}}